### ISSUE TITLE
search: should do the right thing to prevent bouncing results

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/invenio-search#106]
@tsgit pointed out the following piece of Elasticsearch documentation:   https://www.elastic.co/guide/en/elasticsearch/guide/current/_search_options.html#_preference.

In fact, we've discovered that we suffer from this problem, as evidenced by this screencast by @michamos: https://files.gitter.im/inspirehep/ops/Edu1/Screencast_09-10-17_17_55_47.webm. Notice how the "Antibaryon" paper jumps between positions 2 and 3.

The solution is suggested by the same piece of documentation:
>  The problem can be avoided by always using the same shards for the same user, which can be done by setting the preference parameter to an arbitrary string like the user’s session ID.

I believe that `invenio-search` should provide this out-of-the-box, by integrating with `invenio-accounts`.

**Comment by kaplun** [comment]
Ha! That might be connected with the bug we are experiencing when retrieving the whole content of HepData into INSPIRE, where we use the normal Invenio search API, and we specify several queries with different offsets.

**Comment by jacquerie** [comment]
> Ha! That might be connected with the bug we are experiencing when retrieving the whole content of HepData into INSPIRE, where we use the normal Invenio search API, and we specify several queries with different offsets.

@GraemeWatt, have you seen this? Which version of `invenio-search` are you currently deploying?

**Comment by GraemeWatt** [comment]
Thanks, @jacquerie, I hadn't seen this.  I resolved HEPData/hepdata#125 on 6th October by executing an empty search only on the primary shards (https://github.com/HEPData/hepdata/commit/a6eb9367f6fd2b2ecd7f2b2eaba04250c73df043).  We currently use `invenio-search` v1.0.0a9 in production, but we mainly use the Elasticsearch API directly rather than the `invenio-search` API.  The new `with_preference_param()` method indeed looks like a better solution, but I'd need to modify the HEPData code to use the `RecordsSearch` class of the `invenio-search` API.  I opened HEPData/hepdata#128.
